server:
 port: 9011

# eureka 服务端配置
eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
     defaultZone: http://127.0.0.1:9010/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000



