
management:
 security:
  enabled: false #关掉安全认证
 endpoints:
  shutdown:
   enabled: true #是否可通过endpoints关停应用服务
  web:
    base-path: /actuator
    exposure:
      include: '*'
 endpoint:
   health:
     show-details: always

info:
 app:
  name: eureka

spring:
  profiles:
    active: cluster
  application:
    name: eureka



